# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    container_name: dotz-fidelidade-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456